SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = 'dbo' 
                 AND  TABLE_NAME = 'Admins'))
BEGIN

CREATE TABLE [dbo].[Admins](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[UserId] [nvarchar](256) NOT NULL,
	[CreatingDate] DATETIME2 NOT NULL,
	[ModifyDate] DATETIME2
	CONSTRAINT [PK_Admins] PRIMARY KEY CLUSTERED ([Id] ASC )
	WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) 
	ON [PRIMARY]
) ON [PRIMARY]

ALTER TABLE [dbo].[Admins] 
	WITH CHECK ADD  
	CONSTRAINT [FK_Admins_Users] FOREIGN KEY([UserId])
	REFERENCES [dbo].[Users] ([Id])
ON DELETE CASCADE

END